### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by minsooshin**

### CODE REVIEW

**Comment by RaulZhao** [comment]
General question: what is `describe`? Is it from React unit test framework?

**Comment by minsooshin** [comment]
@RaulZhao it is general term for unit tests. I think ruby also using same term on rspec test.
BTW, this syntax is from [Jest](https://facebook.github.io/jest/) which create-react-app is using by default for test framework.

**Review by RaulZhao — APPROVED** [review]
+1

**Comment by RaulZhao** [comment]
Got it. It seems ENZYME is AIRBNB react testing framework.

**Pull request merged**
